name = "Fixora Pro"
client_id = "717095578dc54c2165942dfbbb175dea"
application_url = "https://fixitpro-one.vercel.app"
embedded = true

[access_scopes]
scopes = "read_themes,write_themes"

[auth]
redirect_urls = [
  "https://fixitpro-one.vercel.app/api/auth/callback"
]

[app_proxy]
url = "https://fixitpro-one.vercel.app/api/proxy"
subpath = "reparatie"
prefix = "apps"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/api/webhooks/app-uninstalled"

  [[webhooks.subscriptions]]
  topics = ["app_subscriptions/update"]
  uri = "/api/webhooks/app-subscriptions-update"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "/api/webhooks/gdpr"


[build]
automatically_update_urls_on_dev = true
dev_store_url = "gsm-team-dev.myshopify.com"
