api_version = "2025-01"
uid = "560901b8-4891-13ed-e632-e8440006dd234686563c"

[[extensions]]
type = "theme"
name = "Reparatie Widget"
handle = "repair-widget"

  [[extensions.targeting]]
  target = "section"
